### ISSUE TITLE
Question about how to generate fake semantic features

### ISSUE THREAD

**Issue by vanpersie32** [wenhuchen/ETHZ-Bootstrapped-Captioning#3]
Hey, Thanks for your code. According to the paper, the fake semantic features are the word embedding of visual concepts in the unsupervised sentence. However  according to the code [here](https://github.com/wenhuchen/ETHZ-Bootstrapped-Captioning/blob/3c41fd092dfaa0780fbfc67053a47d59737baf9f/attention_generator/commoncrawl.py#L29)  [here](https://github.com/wenhuchen/ETHZ-Bootstrapped-Captioning/blob/3c41fd092dfaa0780fbfc67053a47d59737baf9f/attention_generator/commoncrawl.py#L44) and [here](https://github.com/wenhuchen/ETHZ-Bootstrapped-Captioning/blob/3c41fd092dfaa0780fbfc67053a47d59737baf9f/attention_generator/commoncrawl.py#L11-L18), you only truncate or pad the unsupervised sentence and save 15 words which are not necessarily visual concepts

**Comment by wenhuchen** [comment]
It seems that you are right, according to this line 45, 
```semantic_flatten[i] = numpy.hstack([salient_mapping[w] for w in word_idx])```
For those words not appearing in the "vocab_glove.pkl", this line will get into error. So the solution is to change line 45 to include only those words appearing in salient mapping. 

Pad the semantic features with zero if the length is not 15, these dummy words won't influence the results since they are all zeros.

**Comment by vanpersie32** [comment]
Sorry, I have mistaken about how you extract the fake semantic features, and your code corresponds to your paper correctly. However I have a little question about your paper. In unsupervised training stage, you truncate or pad the sentence and only save 15 words as visual concepts. However, in supervised training, you detect attributes as visual concepts with MIL. So in the unsupervised stage, the visual concept may be any word from the word vocabulary while in supervised stage, the visual concepts can only be out of attribute vocabulary which is  a subset of word vocabulary. So the definition of visual concepts in unsupervised training stage and supervised training stage  is different. Will the inconsistency affect the performance?

By the way, do you have qq or wechat, can I chat with you there? many thanks
